---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-catalog-frontend
  labels:
    app: data-service-catalog-frontend
spec:
  template:
    spec:
      containers:
        - name: data-service-catalog-frontend
          env:
            - name: NEXTAUTH_URL
              value: https://datatjenestekatalog.staging.fellesdatakatalog.digdir.no
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: data-service-catalog-frontend
                  key: NEXTAUTH_SECRET
            - name: KEYCLOAK_ID
              value: data-service-catalog-frontend
            - name: KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: sso-staging
                  key: SSO_OIDC_ISSUER
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-client-credentials
                  key: DATA_SERVICE_CATALOG_FRONTEND
            - name: DATA_SERVICE_CATALOG_FRONTEND
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: DATA_SERVICE_CATALOG_FRONTEND
            - name: CATALOG_ADMIN_SERVICE_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: CATALOG_ADMIN_SERVICE_BASE_URI
            - name: CATALOG_ADMIN_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: CATALOG_ADMIN_BASE_URI
            - name: ORGANIZATION_CATALOG_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: ORGANIZATION_CATALOG_BASE_URI
            - name: REFERENCE_DATA_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_REFERENCE_DATA_BASE_URI
            - name: ADMIN_GUI_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: ADMIN_GUI_BASE_URI
            - name: FDK_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: FDK_BASE_URI
            - name: DATASERVICE_CATALOG_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: DATASERVICE_CATALOG_BASE_URI
            - name: NEXT_PUBLIC_CATALOG_PORTAL_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-staging
                  key: CATALOG_PORTAL_BASE_URI
