---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/data-service-catalog-frontend
  - data-service-catalog-frontend-ingress.yaml

patchesStrategicMerge:
  - data-service-catalog-frontend-env.yaml
