---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concept-catalog-frontend
  labels:
    app: concept-catalog-frontend
spec:
  template:
    spec:
      containers:
        - name: concept-catalog-frontend
          env:
            - name: NEXTAUTH_URL
              value: https://begrepskatalog.fellesdatakatalog.digdir.no
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: concept-catalog-frontend-prod
                  key: NEXTAUTH_SECRET
            - name: KEYCLOAK_ID
              value: concept-catalog-frontend
            - name: KEYCLOAK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: sso-prod
                  key: SSO_OIDC_ISSUER
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-client-credentials
                  key: CONCEPT_CATALOG_FRONTEND
            - name: CONCEPT_CATALOG_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: CONCEPT_CATALOG_BASE_URI
            - name: CATALOG_COMMENTS_SERVICE_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: CATALOG_COMMENTS_SERVICE_BASE_URI
            - name: CATALOG_HISTORY_SERVICE_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: CATALOG_HISTORY_SERVICE_BASE_URI
            - name: CATALOG_ADMIN_SERVICE_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: CATALOG_ADMIN_SERVICE_BASE_URI
            - name: ORGANIZATION_CATALOG_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: ORGANIZATION_CATALOG_BASE_URI
            - name: CONCEPT_CATALOG_GUI_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: CONCEPT_CATALOGUE_GUI_BASE_URI
            - name: FULLTEXT_SEARCH_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: FDK_FULLTEXT_SEARCH_BASE_URI
            - name: FDK_REGISTRATION_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: FDK_REGISTRATION_BASE_URI
            - name: REFERENCE_DATA_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl-prod
                  key: FDK_REFERENCE_DATA_BASE_URI
