---
apiVersion: v1
kind: Service
metadata:
  name: service-catalog-frontend
spec:
  selector:
    app: service-catalog-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
