---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/catalog-admin-frontend
  - catalog-admin-frontend-ingress.yaml

patchesStrategicMerge:
  - catalog-admin-frontend-env.yaml
