---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concept-catalog-frontend
  labels:
    app: concept-catalog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concept-catalog-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: concept-catalog-frontend
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: concept-catalog-frontend
          image: concept-catalog-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
