---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-concept-catalog-frontend.yaml
  - service-concept-catalog-frontend.yaml
images:
  - name: concept-catalog-frontend
    newName: eu.gcr.io/digdir-fdk-infra/concept-catalog-frontend
    newTag: $(GIT_COMMIT_SHA)
