---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - concept-catalog-frontend-deployment.yaml
  - concept-catalog-frontend-service.yaml
  - catalog-admin-frontend-deployment.yaml
  - catalog-admin-frontend-service.yaml
images:
  - name: concept-catalog-frontend
    newName: eu.gcr.io/digdir-fdk-infra/concept-catalog-frontend
    newTag: $(GIT_COMMIT_SHA)
  - name: catalog-admin-frontend
    newName: eu.gcr.io/digdir-fdk-infra/catalog-admin-frontend
    newTag: $(GIT_COMMIT_SHA)  
