---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base/concept-catalog-frontend
  - concept-catalog-frontend-ingress.yaml

patchesStrategicMerge:
  - concept-catalog-frontend-env.yaml
