---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - data-service-catalog-frontend-deployment.yaml
  - data-service-catalog-frontend-service.yaml
images:
  - name: data-service-catalog-frontend
    newName: eu.gcr.io/digdir-fdk-infra/data-service-catalog-frontend
    newTag: $(GIT_COMMIT_SHA)
