---
apiVersion: v1
kind: Service
metadata:
  name: catalog-admin-frontend
spec:
  selector:
    app: catalog-admin-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
