---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concept-catalog-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: begrepskatalog.staging.fellesdatakatalog.digdir.no
      http:
        paths:
          - backend:
              service:
                name: concept-catalog-frontend
                port:
                  number: 8080
            path: /
            pathType: Prefix
