---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - catalog-portal-frontend-deployment.yaml
  - catalog-portal-frontend-service.yaml
images:
  - name: catalog-portal-frontend
    newName: ghcr.io/informasjonsforvaltning/catalog-frontend/catalog-portal-frontend
    newTag: $(GIT_COMMIT_SHA)
